# Generated by Django 4.2.5 on 2023-09-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("navApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Img",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default=None, upload_to="products")),
            ],
        ),
    ]
